<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Demo_viewer extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Demo_viewer_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('demo_viewer/demo_viewer_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Demo_viewer_model->json();
    }

    public function read($id) 
    {
        $row = $this->Demo_viewer_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'numberofview' => $row->numberofview,
		'created_at' => $row->created_at,
	    );
            $this->load->view('demo_viewer/demo_viewer_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('demo_viewer'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('demo_viewer/create_action'),
	    'id' => set_value('id'),
	    'numberofview' => set_value('numberofview'),
	    'created_at' => set_value('created_at'),
	);
        $this->load->view('demo_viewer/demo_viewer_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'numberofview' => $this->input->post('numberofview',TRUE),
		'created_at' => $this->input->post('created_at',TRUE),
	    );

            $this->Demo_viewer_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('demo_viewer'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Demo_viewer_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('demo_viewer/update_action'),
		'id' => set_value('id', $row->id),
		'numberofview' => set_value('numberofview', $row->numberofview),
		'created_at' => set_value('created_at', $row->created_at),
	    );
            $this->load->view('demo_viewer/demo_viewer_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('demo_viewer'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'numberofview' => $this->input->post('numberofview',TRUE),
		'created_at' => $this->input->post('created_at',TRUE),
	    );

            $this->Demo_viewer_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('demo_viewer'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Demo_viewer_model->get_by_id($id);

        if ($row) {
            $this->Demo_viewer_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('demo_viewer'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('demo_viewer'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('numberofview', 'numberofview', 'trim|required');
	$this->form_validation->set_rules('created_at', 'created at', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Demo_viewer.php */
/* Location: ./application/controllers/Demo_viewer.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-14 08:33:36 */
/* http://harviacode.com */